name: lyte_studios_flutter_ui
description: General UI code blocks specific to LYTE Studios applications
version: 0.0.1
homepage: https://lytestudios.be

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

